apiVersion: investigator.openai.com/v1alpha1
kind: Investigation
metadata:
  name: fllux-kubernetes-mcp
  namespace: investigator
spec:
  query: >-
    Use the Kubernetes MCP server to list the pods in the flux-system namespace
    Analize logs, find any abnormal behaviours, Stuck deployment, bad helm charts etc.
    Check overall GitOps health of cluster.
  agentImage: ghcr.io/arkadiuszspiewak/investigator-agent:latest
  auth:
    authJsonSecretRef:
      name: codex-auth
      key: auth.json
  serviceAccountName: investigator-agent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: rpi
                operator: NotIn
                values:
                  - "true"
          - matchExpressions:
              - key: rpi
                operator: DoesNotExist
  mcpServers:
    - name: kubernetes
      url: http://investigator-investigator-platform-kubernetes.investigator.svc.cluster.local:8080/mcp
