apiVersion: investigator.openai.com/v1alpha1
kind: Investigation
metadata:
  name: test-kubernetes-mcp
  namespace: investigator
spec:
  query: >-
    Use the Kubernetes MCP and Prometheus MCP server to audit pihole namespace.
    Analise why there is such diffrence beetwen ram usage of both pihole instances. Analize in detail why primary pihole has smaller database, why it report 0 blocked domain. Check config and how they are similiar.
    Do not make any changes.
