apiVersion: investigator.openai.com/v1alpha1
kind: Investigation
metadata:
  name: test-kubernetes-mcp
  namespace: investigator
spec:
  query: >-
    Use the Kubernetes MCP and Prometheus MCP server to audit pihole namespace.
    Analise why there is such diffrence beetwen ram usage of both pihole instances. Analize in detail why primary pihole has smaller database, why it report 0 blocked domain. Check config and how they are similiar.
    Do not make any changes.
  agentImage: ghcr.io/arkadiuszspiewak/investigator-agent:latest
  auth:
    authJsonSecretRef:
      name: codex-auth
      key: auth.json
  serviceAccountName: investigator-agent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: rpi
                operator: NotIn
                values:
                  - "true"
          - matchExpressions:
              - key: rpi
                operator: DoesNotExist
  mcpServers:
    - name: kubernetes
      url: http://investigator-investigator-platform-kubernetes.investigator.svc.cluster.local:8080/mcp
    - name: prometheus
      url: http://investigator-investigator-platform-prometheus.investigator.svc.cluster.local:8080/mcp
