# syntax=docker/dockerfile:1
FROM rust:1.97.1-bookworm AS builder
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY apps ./apps
COPY crates ./crates
COPY servers ./servers
RUN cargo build --locked --release --package investigator

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=builder --chown=65532:65532 /src/target/release/investigator /usr/local/bin/investigator
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/investigator"]
