use std::{
    io::Write,
    path::{Path, PathBuf},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use clap::{ArgGroup, Parser};
use investigator::crd::{
    AgentAuth, Investigation, InvestigationQuestion, InvestigationSpec, McpServer,
};
use kube::{
    Api, Client,
    api::{Patch, PatchParams, PostParams},
};
use serde::Deserialize;

#[derive(Parser)]
#[command(
    version,
    about = "Open an investigation conversation or run one question"
)]
#[command(group(ArgGroup::new("mode").required(true).args(["run_investigation", "one_shot"])))]
struct Args {
    /// Configuration file. Defaults to ~/.investigator-cli/config.json.
    #[arg(short, long)]
    config: Option<PathBuf>,
    /// Start an active conversation with this Investigation name.
    #[arg(long, value_name = "NAME")]
    run_investigation: Option<String>,
    /// Run one question, print its answer, and exit.
    #[arg(long, value_name = "QUESTION")]
    one_shot: Option<String>,
    /// Optional Investigation name for --one-shot; one is generated by default.
    #[arg(long, requires = "one_shot")]
    name: Option<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Config {
    #[serde(default = "default_namespace")]
    namespace: String,
    #[serde(default = "default_agent_image")]
    agent_image: String,
    #[serde(default = "default_service_account")]
    service_account_name: String,
    auth: AgentAuth,
    #[serde(default)]
    mcp_servers: Vec<McpServer>,
    #[serde(default)]
    node_selector: std::collections::BTreeMap<String, String>,
    #[serde(default)]
    affinity: Option<serde_json::Value>,
    #[serde(default)]
    tolerations: Vec<serde_json::Value>,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();
    let config_path = args.config.unwrap_or(default_config_path()?);
    let config = load_config(&config_path)?;
    let api = Api::<Investigation>::namespaced(Client::try_default().await?, &config.namespace);

    if let Some(name) = args.run_investigation {
        println!("Starting investigation `{name}`. Enter the initial question.");
        let Some(query) = prompt("investigation> ")? else {
            return Ok(());
        };
        create_investigation(&api, &name, query, &config).await?;
        conversation(&api, &name).await?;
    } else if let Some(query) = args.one_shot {
        let name = args.name.unwrap_or_else(generated_name);
        create_investigation(&api, &name, query, &config).await?;
        let investigation = wait_for_answer(&api, &name, 0).await?;
        print_answer(&investigation, 0);
    }
    Ok(())
}

fn load_config(path: &Path) -> Result<Config, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path).map_err(|error| {
        format!(
            "could not read configuration {}: {error}. Create it or pass --config PATH",
            path.display()
        )
    })?;
    let config: Config = serde_json::from_str(&content)?;
    if config.auth.api_key_secret_ref.is_some() == config.auth.auth_json_secret_ref.is_some() {
        return Err(
            "config auth must contain exactly one of apiKeySecretRef or authJsonSecretRef".into(),
        );
    }
    Ok(config)
}

fn default_config_path() -> Result<PathBuf, &'static str> {
    let home = std::env::var_os("HOME").ok_or("HOME is not set; pass --config PATH")?;
    Ok(PathBuf::from(home)
        .join(".investigator-cli")
        .join("config.json"))
}

async fn create_investigation(
    api: &Api<Investigation>,
    name: &str,
    query: String,
    config: &Config,
) -> Result<(), kube::Error> {
    let investigation = Investigation::new(
        name,
        InvestigationSpec {
            query,
            questions: vec![],
            agent_image: config.agent_image.clone(),
            auth: config.auth.clone(),
            mcp_servers: config.mcp_servers.clone(),
            service_account_name: config.service_account_name.clone(),
            node_selector: config.node_selector.clone(),
            affinity: config.affinity.clone(),
            tolerations: config.tolerations.clone(),
        },
    );
    api.create(&PostParams::default(), &investigation).await?;
    Ok(())
}

async fn conversation(
    api: &Api<Investigation>,
    name: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut shown_answers = 0;
    loop {
        let investigation = wait_for_answer(api, name, shown_answers).await?;
        print_answer(&investigation, shown_answers);
        let status = investigation.status.as_ref().expect("completed status");
        if status.phase.as_deref() == Some("Failed") {
            break;
        }
        shown_answers = status.answers.len() + 1;
        let Some(question) = prompt("follow-up (empty to exit)> ")? else {
            break;
        };
        let mut questions = investigation.spec.questions;
        questions.push(InvestigationQuestion {
            id: format!("q-{}", timestamp_millis()),
            query: question,
        });
        api.patch(
            name,
            &PatchParams::default(),
            &Patch::Merge(serde_json::json!({"spec": {"questions": questions}})),
        )
        .await?;
    }
    Ok(())
}

fn prompt(label: &str) -> Result<Option<String>, std::io::Error> {
    print!("\n{label}");
    std::io::stdout().flush()?;
    let mut value = String::new();
    std::io::stdin().read_line(&mut value)?;
    let value = value.trim();
    Ok((!value.is_empty()).then(|| value.to_owned()))
}

fn print_answer(investigation: &Investigation, shown: usize) {
    let status = investigation.status.as_ref().expect("completed status");
    let answer = if shown == 0 {
        status.result.as_deref().unwrap_or("Investigation failed")
    } else {
        &status.answers[shown - 1].result
    };
    println!("\n{answer}");
}

async fn wait_for_answer(
    api: &Api<Investigation>,
    name: &str,
    shown: usize,
) -> Result<Investigation, kube::Error> {
    loop {
        let investigation = api.get(name).await?;
        if let Some(status) = &investigation.status {
            let available = usize::from(status.result.is_some()) + status.answers.len();
            if available > shown || status.phase.as_deref() == Some("Failed") {
                return Ok(investigation);
            }
        }
        tokio::time::sleep(Duration::from_secs(2)).await;
    }
}

fn generated_name() -> String {
    format!("cli-{}", timestamp_millis())
}
fn timestamp_millis() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}
fn default_namespace() -> String {
    "default".to_owned()
}
fn default_agent_image() -> String {
    "ghcr.io/arkadiuszspiewak/investigator-agent:latest".to_owned()
}
fn default_service_account() -> String {
    "investigator-agent".to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minimal_config_uses_defaults() {
        let config: Config = serde_json::from_str(
            r#"{"auth":{"apiKeySecretRef":{"name":"openai","key":"api-key"}}}"#,
        )
        .unwrap();
        assert_eq!(config.namespace, "default");
        assert_eq!(config.service_account_name, "investigator-agent");
        assert!(config.mcp_servers.is_empty());
    }
}
