mod error;

use std::{
    io::Write,
    path::{Path, PathBuf},
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use clap::{ArgGroup, Parser};
use error::AppError;
use investigator::crd::{
    AgentAuth, Investigation, InvestigationQuestion, InvestigationSpec, McpServer,
};
use kube::{
    Api, Client,
    api::{Patch, PatchParams, PostParams},
};
use serde::Deserialize;

#[derive(Parser)]
#[command(
    version,
    about = "Open an investigation conversation or run one question"
)]
#[command(group(ArgGroup::new("mode").required(true).args(["run_investigation", "one_shot"])))]
struct Args {
    /// Configuration file. Defaults to ~/.investigator-cli/config.json.
    #[arg(short, long)]
    config: Option<PathBuf>,
    /// Start an active conversation with this Investigation name.
    #[arg(long, value_name = "NAME")]
    run_investigation: Option<String>,
    /// Run one question, print its answer, and exit.
    #[arg(long, value_name = "QUESTION")]
    one_shot: Option<String>,
    /// Optional Investigation name for --one-shot; one is generated by default.
    #[arg(long, requires = "one_shot")]
    name: Option<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Config {
    #[serde(default = "default_namespace")]
    namespace: String,
    #[serde(default = "default_agent_image")]
    agent_image: String,
    #[serde(default = "default_service_account")]
    service_account_name: String,
    auth: AgentAuth,
    #[serde(default)]
    mcp_servers: Vec<McpServer>,
}

#[tokio::main]
async fn main() -> std::process::ExitCode {
    tracing_subscriber::fmt()
        .json()
        .flatten_event(true)
        .with_current_span(false)
        .with_span_list(false)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "investigator_cli=info".into()),
        )
        .init();

    match run().await {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(error) => {
            tracing::error!(event = "application_failed", error = %error);
            std::process::ExitCode::FAILURE
        }
    }
}

async fn run() -> Result<(), AppError> {
    let args = Args::parse();
    let config_path = args.config.unwrap_or(default_config_path()?);
    let config = load_config(&config_path)?;
    let api = Api::<Investigation>::namespaced(Client::try_default().await?, &config.namespace);

    if let Some(name) = args.run_investigation {
        if let Some(existing) = api.get_opt(&name).await? {
            tracing::info!(event = "investigation_resumed", investigation_name = name,);
            conversation(&api, &name, Some(existing)).await?;
        } else {
            tracing::info!(event = "investigation_started", investigation_name = name,);
            let Some(query) = prompt("investigation> ")? else {
                return Ok(());
            };
            match create_investigation(&api, &name, query, &config).await {
                Ok(()) => conversation(&api, &name, None).await?,
                Err(kube::Error::Api(response)) if response.code == 409 => {
                    tracing::warn!(
                        event = "investigation_create_conflict",
                        investigation_name = name,
                        action = "resume",
                    );
                    conversation(&api, &name, Some(api.get(&name).await?)).await?;
                }
                Err(error) => return Err(error.into()),
            }
        }
    } else if let Some(query) = args.one_shot {
        let name = args.name.unwrap_or_else(generated_name);
        create_investigation(&api, &name, query, &config).await?;
        let investigation = wait_for_answer(&api, &name, 0).await?;
        print_answer(&investigation, 0)?;
    }
    Ok(())
}

fn load_config(path: &Path) -> Result<Config, AppError> {
    let content = std::fs::read_to_string(path).map_err(|source| AppError::ReadConfig {
        path: path.to_owned(),
        source,
    })?;
    let config: Config = serde_json::from_str(&content)?;
    if config.auth.api_key_secret_ref.is_some() == config.auth.auth_json_secret_ref.is_some() {
        return Err(AppError::InvalidAuth);
    }
    Ok(config)
}

fn default_config_path() -> Result<PathBuf, AppError> {
    let home = std::env::var_os("HOME").ok_or(AppError::MissingHome)?;
    Ok(PathBuf::from(home)
        .join(".investigator-cli")
        .join("config.json"))
}

async fn create_investigation(
    api: &Api<Investigation>,
    name: &str,
    query: String,
    config: &Config,
) -> Result<(), kube::Error> {
    let investigation = Investigation::new(
        name,
        InvestigationSpec {
            query,
            questions: vec![],
            agent_image: config.agent_image.clone(),
            auth: config.auth.clone(),
            mcp_servers: config.mcp_servers.clone(),
            service_account_name: config.service_account_name.clone(),
        },
    );
    api.create(&PostParams::default(), &investigation).await?;
    Ok(())
}

async fn conversation(
    api: &Api<Investigation>,
    name: &str,
    existing: Option<Investigation>,
) -> Result<(), AppError> {
    let mut shown_answers = existing.as_ref().map(available_answers).unwrap_or(0);
    let mut waiting = existing.as_ref().map(has_pending_turn).unwrap_or(true);
    let mut current = existing;

    if let Some(investigation) = current.as_ref() {
        print_history(investigation);
        if investigation
            .status
            .as_ref()
            .and_then(|status| status.phase.as_deref())
            == Some("Failed")
        {
            return Ok(());
        }
    }

    loop {
        if waiting {
            let investigation = wait_for_answer(api, name, shown_answers).await?;
            print_answer(&investigation, shown_answers)?;
            shown_answers = available_answers(&investigation);
            current = Some(investigation);
        }
        let investigation = current.take().ok_or(AppError::MissingConversationState)?;
        let status = investigation
            .status
            .as_ref()
            .ok_or(AppError::MissingCompletedStatus)?;
        if status.phase.as_deref() == Some("Failed") {
            break;
        }
        let Some(question) = prompt("follow-up (empty to exit)> ")? else {
            break;
        };
        let mut questions = investigation.spec.questions;
        questions.push(InvestigationQuestion {
            id: format!("q-{}", timestamp_millis()),
            query: question,
        });
        api.patch(
            name,
            &PatchParams::default(),
            &Patch::Merge(serde_json::json!({"spec": {"questions": questions}})),
        )
        .await?;
        waiting = true;
    }
    Ok(())
}

fn available_answers(investigation: &Investigation) -> usize {
    investigation.status.as_ref().map_or(0, |status| {
        usize::from(status.result.is_some()) + status.answers.len()
    })
}

fn has_pending_turn(investigation: &Investigation) -> bool {
    let Some(status) = investigation.status.as_ref() else {
        return true;
    };
    status.result.is_none()
        || investigation.spec.questions.len() > status.answers.len()
        || matches!(status.phase.as_deref(), Some("Pending" | "Running"))
}

fn print_history(investigation: &Investigation) {
    println!("\ninvestigation> {}", investigation.spec.query);
    let Some(status) = investigation.status.as_ref() else {
        println!("\nWaiting for the initial answer...");
        return;
    };
    if let Some(result) = status.result.as_deref() {
        println!("\n{result}");
    }
    for question in &investigation.spec.questions {
        println!("\nfollow-up> {}", question.query);
        if let Some(answer) = status
            .answers
            .iter()
            .find(|answer| answer.question_id == question.id)
        {
            println!("\n{}", answer.result);
        } else {
            println!("\nWaiting for an answer...");
        }
    }
}

fn prompt(label: &str) -> Result<Option<String>, std::io::Error> {
    print!("\n{label}");
    std::io::stdout().flush()?;
    let mut value = String::new();
    std::io::stdin().read_line(&mut value)?;
    let value = value.trim();
    Ok((!value.is_empty()).then(|| value.to_owned()))
}

fn print_answer(investigation: &Investigation, shown: usize) -> Result<(), AppError> {
    let status = investigation
        .status
        .as_ref()
        .ok_or(AppError::MissingCompletedStatus)?;
    let answer = if shown == 0 {
        status.result.as_deref().unwrap_or("Investigation failed")
    } else {
        &status.answers[shown - 1].result
    };
    println!("\n{answer}");
    Ok(())
}

async fn wait_for_answer(
    api: &Api<Investigation>,
    name: &str,
    shown: usize,
) -> Result<Investigation, kube::Error> {
    loop {
        let investigation = api.get(name).await?;
        if let Some(status) = &investigation.status {
            let available = usize::from(status.result.is_some()) + status.answers.len();
            if available > shown || status.phase.as_deref() == Some("Failed") {
                return Ok(investigation);
            }
        }
        tokio::time::sleep(Duration::from_secs(2)).await;
    }
}

fn generated_name() -> String {
    format!("cli-{}", timestamp_millis())
}
fn timestamp_millis() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}
fn default_namespace() -> String {
    "default".to_owned()
}
fn default_agent_image() -> String {
    "ghcr.io/arkadiuszspiewak/investigator-agent:latest".to_owned()
}
fn default_service_account() -> String {
    "investigator-agent".to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use investigator::crd::{InvestigationAnswer, InvestigationStatus};

    #[test]
    fn minimal_config_uses_defaults() {
        let config: Config = serde_json::from_str(
            r#"{"auth":{"apiKeySecretRef":{"name":"openai","key":"api-key"}}}"#,
        )
        .unwrap();
        assert_eq!(config.namespace, "default");
        assert_eq!(config.service_account_name, "investigator-agent");
        assert!(config.mcp_servers.is_empty());
    }

    #[test]
    fn completed_existing_investigation_is_ready_for_a_follow_up() {
        let investigation = Investigation::new(
            "existing",
            InvestigationSpec {
                query: "initial".into(),
                questions: vec![InvestigationQuestion {
                    id: "q1".into(),
                    query: "follow-up".into(),
                }],
                agent_image: default_agent_image(),
                auth: AgentAuth {
                    api_key_secret_ref: None,
                    auth_json_secret_ref: None,
                },
                mcp_servers: vec![],
                service_account_name: default_service_account(),
            },
        );
        let mut investigation = investigation;
        investigation.status = Some(InvestigationStatus {
            phase: Some("Succeeded".into()),
            result: Some("initial answer".into()),
            answers: vec![InvestigationAnswer {
                question_id: "q1".into(),
                result: "follow-up answer".into(),
            }],
            ..Default::default()
        });

        assert_eq!(available_answers(&investigation), 2);
        assert!(!has_pending_turn(&investigation));
    }
}
