{{- if .Values.investigator.enabled }}
{{- if .Values.investigator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "investigator-platform.controllerServiceAccount" . }}
  labels:
    {{- include "investigator-platform.labels" . | nindent 4 }}
  {{- with .Values.investigator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.investigator.agentServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "investigator-platform.agentServiceAccount" . }}
  labels:
    {{- include "investigator-platform.labels" . | nindent 4 }}
  {{- with .Values.investigator.agentServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
