name: Build investigator-agent-bedrock

on:
  pull_request:
    paths:
      - agents/bedrock/**
      - .github/workflows/_build-agent.yml
      - .github/workflows/build-agent-bedrock.yml
  push:
    tags: [agent-bedrock-v*]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/_build-agent.yml
    with:
      agent: bedrock
    secrets: inherit
